# Generated by Django 5.1.2 on 2024-11-05 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryModel",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("subject", models.CharField(max_length=32)),
                ("tag", models.CharField(max_length=32)),
                ("progress", models.FloatField()),
                (
                    "UID",
                    models.ForeignKey(
                        db_column="UID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.usermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionsModel",
            fields=[
                ("QID", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("explanation", models.TextField()),
                ("difficulty", models.IntegerField()),
                ("time_require", models.IntegerField()),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("choice", "Choice Question"),
                            ("blank", "Blank Question"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "history_id",
                    models.ForeignKey(
                        db_column="history_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Questions.historymodel",
                    ),
                ),
            ],
            options={
                "db_table": "Questions",
            },
        ),
    ]
