# Generated by Django 5.1.2 on 2024-11-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Questions", "0002_alter_historymodel_table"),
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlankQuestionModel",
            fields=[
                (
                    "QID",
                    models.OneToOneField(
                        db_column="QID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="Questions.questionsmodel",
                    ),
                ),
                ("correct_answer", models.TextField()),
            ],
            options={
                "db_table": "BlankQuestion",
            },
        ),
        migrations.CreateModel(
            name="ChoiceQuestionModel",
            fields=[
                (
                    "QID",
                    models.OneToOneField(
                        db_column="QID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="Questions.questionsmodel",
                    ),
                ),
                ("option1", models.TextField()),
                ("option2", models.TextField()),
                ("option3", models.TextField()),
                ("option4", models.TextField()),
                ("correct_answers", models.JSONField()),
            ],
            options={
                "db_table": "ChoiceQuestion",
            },
        ),
        migrations.CreateModel(
            name="AttemptModel",
            fields=[
                ("attempt_id", models.AutoField(primary_key=True, serialize=False)),
                ("attempt_time", models.DateTimeField(auto_now_add=True)),
                ("user_answers", models.JSONField(blank=True, null=True)),
                ("user_answer", models.TextField(blank=True, null=True)),
                ("is_correct", models.BooleanField()),
                (
                    "QID",
                    models.ForeignKey(
                        db_column="QID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Questions.questionsmodel",
                    ),
                ),
                (
                    "UID",
                    models.ForeignKey(
                        db_column="UID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.usermodel",
                    ),
                ),
                (
                    "history_id",
                    models.ForeignKey(
                        db_column="history_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Questions.historymodel",
                    ),
                ),
            ],
            options={
                "db_table": "Attempt",
            },
        ),
    ]
