# Generated by Django 5.1.2 on 2024-11-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Questions", "0003_blankquestionmodel_choicequestionmodel_attemptmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionsmodel",
            name="type",
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name="questionsmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["choice", "blank"])), name="type_check"
            ),
        ),
    ]
