# Generated by Django 5.1.2 on 2024-11-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Questions", "0005_remove_questionsmodel_type_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historymodel",
            name="progress",
            field=models.FloatField(default=0),
        ),
    ]
