# Generated by Django 5.1.2 on 2024-11-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="role",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name="usermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["teacher", "student"])),
                name="role_check",
            ),
        ),
    ]
