# Generated by Django 5.1.2 on 2024-11-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_alter_usermodel_role"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="usermodel",
            name="role_check",
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="role",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddConstraint(
            model_name="usermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["teacher", "student"])),
                name="Users_role_check",
            ),
        ),
    ]
